substitutions:
  name: tianpower-bms-ble
  bms0: "${name} device0"
  bms1: "${name} device1"
  device_description: "Monitor two Tianpower Battery Management Systems via BLE"
  external_components_source: github://syssi/esphome-tianpower-bms@main
  bms0_mac_address: !secret bms0_mac_address
  bms1_mac_address: !secret bms1_mac_address

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-tianpower-bms"
    version: 2.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - switch.turn_off: ble_client_switch1
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:
  reboot_timeout: 0s

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

tianpower_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 10s
  - ble_client_id: client1
    id: bms1
    update_interval: 10s

binary_sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    limiting_current:
      name: "${bms0} limiting current"
    balancing:
      name: "${bms0} balancing"
    cell_balancing_1:
      name: "${bms0} cell 1 balancing"
    cell_balancing_2:
      name: "${bms0} cell 2 balancing"
    cell_balancing_3:
      name: "${bms0} cell 3 balancing"
    cell_balancing_4:
      name: "${bms0} cell 4 balancing"
    cell_balancing_5:
      name: "${bms0} cell 5 balancing"
    cell_balancing_6:
      name: "${bms0} cell 6 balancing"
    cell_balancing_7:
      name: "${bms0} cell 7 balancing"
    cell_balancing_8:
      name: "${bms0} cell 8 balancing"
    cell_balancing_9:
      name: "${bms0} cell 9 balancing"
    cell_balancing_10:
      name: "${bms0} cell 10 balancing"
    cell_balancing_11:
      name: "${bms0} cell 11 balancing"
    cell_balancing_12:
      name: "${bms0} cell 12 balancing"
    cell_balancing_13:
      name: "${bms0} cell 13 balancing"
    cell_balancing_14:
      name: "${bms0} cell 14 balancing"
    cell_balancing_15:
      name: "${bms0} cell 15 balancing"
    cell_balancing_16:
      name: "${bms0} cell 16 balancing"

  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    limiting_current:
      name: "${bms1} limiting current"
    balancing:
      name: "${bms1} balancing"
    cell_balancing_1:
      name: "${bms1} cell 1 balancing"
    cell_balancing_2:
      name: "${bms1} cell 2 balancing"
    cell_balancing_3:
      name: "${bms1} cell 3 balancing"
    cell_balancing_4:
      name: "${bms1} cell 4 balancing"
    cell_balancing_5:
      name: "${bms1} cell 5 balancing"
    cell_balancing_6:
      name: "${bms1} cell 6 balancing"
    cell_balancing_7:
      name: "${bms1} cell 7 balancing"
    cell_balancing_8:
      name: "${bms1} cell 8 balancing"
    cell_balancing_9:
      name: "${bms1} cell 9 balancing"
    cell_balancing_10:
      name: "${bms1} cell 10 balancing"
    cell_balancing_11:
      name: "${bms1} cell 11 balancing"
    cell_balancing_12:
      name: "${bms1} cell 12 balancing"
    cell_balancing_13:
      name: "${bms1} cell 13 balancing"
    cell_balancing_14:
      name: "${bms1} cell 14 balancing"
    cell_balancing_15:
      name: "${bms1} cell 15 balancing"
    cell_balancing_16:
      name: "${bms1} cell 16 balancing"

sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    voltage_protection_bitmask:
      name: "${bms0} voltage protection bitmask"
    current_protection_bitmask:
      name: "${bms0} current protection bitmask"
    temperature_protection_bitmask:
      name: "${bms0} temperature protection bitmask"
    error_bitmask:
      name: "${bms0} error bitmask"
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    state_of_charge:
      name: "${bms0} state of charge"
    nominal_capacity:
      name: "${bms0} nominal capacity"
    charging_cycles:
      name: "${bms0} charging cycles"
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    average_temperature:
      name: "${bms0} average temperature"
    ambient_temperature:
      name: "${bms0} ambient temperature"
    mosfet_temperature:
      name: "${bms0} mosfet temperature"
    state_of_health:
      name: "${bms0} state of health"
    alarm_bitmask:
      name: "${bms0} alarm bitmask"
    temperature_1:
      name: "${bms0} temperature 1"
    temperature_2:
      name: "${bms0} temperature 2"
    temperature_3:
      name: "${bms0} temperature 3"
    temperature_4:
      name: "${bms0} temperature 4"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
    cell_voltage_9:
      name: "${bms0} cell voltage 9"
    cell_voltage_10:
      name: "${bms0} cell voltage 10"
    cell_voltage_11:
      name: "${bms0} cell voltage 11"
    cell_voltage_12:
      name: "${bms0} cell voltage 12"
    cell_voltage_13:
      name: "${bms0} cell voltage 13"
    cell_voltage_14:
      name: "${bms0} cell voltage 14"
    cell_voltage_15:
      name: "${bms0} cell voltage 15"
    cell_voltage_16:
      name: "${bms0} cell voltage 16"
    balancing_bitmask:
      name: "${bms0} balancing bitmask"

  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms1
    voltage_protection_bitmask:
      name: "${bms1} voltage protection bitmask"
    current_protection_bitmask:
      name: "${bms1} current protection bitmask"
    temperature_protection_bitmask:
      name: "${bms1} temperature protection bitmask"
    error_bitmask:
      name: "${bms1} error bitmask"
    total_voltage:
      name: "${bms1} total voltage"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    state_of_charge:
      name: "${bms1} state of charge"
    nominal_capacity:
      name: "${bms1} nominal capacity"
    charging_cycles:
      name: "${bms1} charging cycles"
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    average_temperature:
      name: "${bms1} average temperature"
    ambient_temperature:
      name: "${bms1} ambient temperature"
    mosfet_temperature:
      name: "${bms1} mosfet temperature"
    state_of_health:
      name: "${bms1} state of health"
    alarm_bitmask:
      name: "${bms1} alarm bitmask"
    temperature_1:
      name: "${bms1} temperature 1"
    temperature_2:
      name: "${bms1} temperature 2"
    temperature_3:
      name: "${bms1} temperature 3"
    temperature_4:
      name: "${bms1} temperature 4"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
    cell_voltage_9:
      name: "${bms1} cell voltage 9"
    cell_voltage_10:
      name: "${bms1} cell voltage 10"
    cell_voltage_11:
      name: "${bms1} cell voltage 11"
    cell_voltage_12:
      name: "${bms1} cell voltage 12"
    cell_voltage_13:
      name: "${bms1} cell voltage 13"
    cell_voltage_14:
      name: "${bms1} cell voltage 14"
    cell_voltage_15:
      name: "${bms1} cell voltage 15"
    cell_voltage_16:
      name: "${bms1} cell voltage 16"
    balancing_bitmask:
      name: "${bms1} balancing bitmask"

switch:
  - platform: ble_client0
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"
    id: ble_client_switch0

  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"
    id: ble_client_switch1

text_sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    software_version:
      name: "${bms0} software version"
    device_model:
      name: "${bms0} device model"
    voltage_protection:
      name: "${bms0} voltage protection"
    current_protection:
      name: "${bms0} current protection"
    temperature_protection:
      name: "${bms0} temperature protection"
    errors:
      name: "${bms0} errors"

  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms1
    software_version:
      name: "${bms1} software version"
    device_model:
      name: "${bms1} device model"
    voltage_protection:
      name: "${bms1} voltage protection"
    current_protection:
      name: "${bms1} current protection"
    temperature_protection:
      name: "${bms1} temperature protection"
    errors:
      name: "${bms1} errors"
